### PR TITLE
chore(brew): create brew release script

### PR DESCRIPTION
**Pull request by campionfellin**
Part of https://github.com/awslabs/cdk8s/issues/49

Will update READMEs in another PR.

This script for now is meant to be run locally. Will update it in the future to run in the Github Actions.

Tested it with `cdk8s 0.17.0` PR, which is here:  https://github.com/Homebrew/homebrew-core/pull/52032

Signed-off-by: campionfellin <campionfellin@gmail.com>

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by SMillerDev** [comment]
There are existing github actions to make a release on new tags

**Comment by campionfellin** [comment]
@SMillerDev I see a few in the GH Marketplace: https://github.com/marketplace?type=actions&query=homebrew

Any official recommendation by homebrew team?

**Comment by chenrui333** [comment]
@campionfellin this can be better one (simply a github action flow would be enough):
https://github.com/mislav/bump-homebrew-formula-action

```

on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula-name: cdk8s
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
```

**Comment by campionfellin** [comment]
@chenrui333 thanks for the suggestion :)

@eladb let me know if you need a personal access token!

**Comment by chenrui333** [comment]
I think the tag trigger is better than master push trigger.
```
name: Release
on:
  push:
    tags: 'v*'
```

**Comment by SMillerDev** [comment]
I think it should. Either the one from mislav or dawidd6 would be good to use. The one from dawidd6 uses brew components under the hood so might be easier.

**Comment by campionfellin** [comment]
I agree that it should be a separate workflow, as we may not want a new version for every commit. We'll have to make some changes to the `release-github.sh` script, as we cannot trigger a workflow run (release to homebrew) from another workflow run (release) when using the `$GITHUB_TOKEN`:

```
If you would like to trigger a workflow from a workflow run, you can trigger the event
using a personal access token. You'll need to create a personal access token and store
it as a secret in your repository. To minimize your GitHub Actions usage costs, ensure
that you don't create recursive or unintended workflow runs
```

from [here](https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token)

This makes me also think that we should really change our main `release.yml` action to also only trigger on new versions as well. Right now, it is "successfully" running every time, but each `release_maven, release_npm, etc` fails.

I'll take a look into how we can do this. I think it may be as simple as changing the token we use in `github-release.sh` and triggering the rest of releases based on that.

**Comment by eladb** [comment]
> This makes me also think that we should really change our main `release.yml` action to also only trigger on new versions as well. Right now, it is "successfully" running every time, but each `release_maven, release_npm, etc` fails.

The current model where we opportunistically release on every commit is intentional and aligned with how we do it in the AWS CDK. It is based on the bump workflow where a release is triggered by a simple bump commit to the repo that includes both the CHANGELOG change and the version change.

> we cannot trigger a workflow run (release to homebrew) from another workflow run (release)

Got it, so maybe we can just add a small check before we publish the PR to homebrew that will only do that if the version is not already released?

**Comment by campionfellin** [comment]
We could probably add a check like this: 
```
release_homebrew:
    name: Release to Homebrew
    if startsWith(github.ref, 'v')
.
.
.
```

Or we could `exit 1` here:

https://github.com/awslabs/cdk8s/blob/fd8f75359b37a6f76368d498f00d8dc615650423/tools/release-github.sh#L11-L16

Which would stop the workflow after this step in the `build_artifact` job:

https://github.com/awslabs/cdk8s/blob/fd8f75359b37a6f76368d498f00d8dc615650423/.github/workflows/release.yml#L34

**Comment by campionfellin** [comment]
Looks like the `if` check worked in the negative case! (thanks for fixing the quotes). We'll have to do a release of `0.18.0` to check the other case.

**Pull request merged**
