### PR TITLE
fix: #406: Update Java imports

### LINKED ISSUE #406: Java Getting Started uses wrong imports
### Description of the bug:
The java getting started doc. references some non existent Kube* API.

### Reproduction Steps:

For example those [documented](https://github.com/awslabs/cdk8s/blob/master/docs/getting-started.md) imports: 

```
import imports.k8s.KubeService;
import imports.k8s.KubeServiceOptions;
```

don't resolve after doing a:
* `cdk8s init java-app`
* followed by a `cdk8s import `

### Other:

Also, there are some unused imports in the WebService example.

--- 

This is :bug: Bug Report

### PR DESCRIPTION
**Pull request by anthonydahanne**
*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Comment by eladb** [comment]
Can you please elaborate why this is needed?

**Comment by anthonydahanne** [comment]
Hello, as described in #406 , the code in the documentation does not compile, because the Api from the import is not prefixed with `Kube` anymore

**Comment by iliapolo** [comment]
@anthonydahanne I think there is some confusion around the latest import changes. The current version does indeed add the `Kube` prefix to all imported resources. I suspect you were probably testing against and older version of the import.

There are still however other issues with the java example which i've addressed in this [PR](https://github.com/awslabs/cdk8s/pull/410/files) so im going to close this one out.

Thanks for getting our attention :)

**Comment by anthonydahanne** [comment]
Hello @iliapolo - that's correct, I was using 0.33 from brew, and 1.0.0-beta3 actually changed the API.

Sure, let's move the work / discussion to your PR.

Thanks

**Comment by iliapolo** [comment]
@anthonydahanne Yes it seems the brew formula is not updated. @campionfellin already opened an [issue](https://github.com/awslabs/cdk8s/issues/409) for that 👍

**Pull request closed without merging**
